### ISSUE TITLE
Pip install fails

### ISSUE THREAD

**Issue by mcarlton00** [crustymonkey/py-sonic#22]
I've ran into this on 2 machines so far.  Could it possibly be because `requirements.txt` is empty?
```
% pip install py-sonic
Collecting py-sonic
  Downloading https://files.pythonhosted.org/packages/e7/ae/4a48ca9010d8f69714f01a223de66949cbe52c233d231479dcaabb4df1a7/py-sonic-0.7.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mgl7m7fu/py-sonic/setup.py", line 25, in <module>
        requirements = [line for line in open(req_file) if line]
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-mgl7m7fu/py-sonic/requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-mgl7m7fu/py-sonic/
```

Note: running `python setup.py install` works without errors

**Comment by crustymonkey** [comment]
Thanks for reporting this. I apparently missed that file in the manifest.  I just tested this and it is working again.
